import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, CheckSquare, Clock, Plus } from 'lucide-react';

export default function Dashboard() {
  const [sessions, setSessions] = useState([]); const [tasks, setTasks] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { async function load() { try { const [s, t] = await Promise.all([fetch('/api/sessions'), fetch('/api/tasks')]); if (!s.ok || !t.ok) throw new Error('Could not load dashboard data.'); setSessions(await s.json()); setTasks(await t.json()); } catch (err) { setError(err.message); } finally { setLoading(false); } } load(); }, []);
  if (loading) return <p className="text-slate-500">Loading dashboard…</p>; if (error) return <div className="alert-error">{error}</div>;
  return <div className="space-y-8"><section className="flex flex-col sm:flex-row justify-between gap-4"><div><h1 className="text-3xl font-bold">Today</h1><p className="mt-1 text-slate-500">Manage your learning sessions and tasks.</p></div><Link to="/new-session" className="button-primary"><Plus size={18} /> New Learning Session</Link></section><div className="grid grid-cols-1 lg:grid-cols-3 gap-8"><section className="lg:col-span-2 card"><h2 className="card-title"><CheckSquare className="text-indigo-600" /> Learning Tasks ({tasks.length})</h2>{tasks.length === 0 ? <Empty text="No learning tasks yet." /> : <div className="space-y-3">{tasks.map(task => <article key={task.id} className="task"><div><p className="font-semibold">{task.title} <span className="badge">{task.priority}</span></p>{task.description && <p className="text-sm text-slate-600 mt-1">{task.description}</p>}</div><span className="text-xs text-slate-500 flex items-center gap-1"><Clock size={14} />{task.durationMinutes}m</span></article>)}</div>}</section><aside className="card"><h2 className="card-title"><BookOpen className="text-indigo-600" /> Recent Sessions</h2>{sessions.length === 0 ? <div className="empty-state">No learning sessions yet.<br /><Link to="/new-session" className="back-link mt-3">Create your first learning session.</Link></div> : <div className="space-y-3">{sessions.map(session => <Link className="session block hover:border-indigo-200" to={`/sessions/${session.id}`} key={session.id}><div className="flex justify-between gap-2"><span className="badge">{session.status}</span><span className="text-xs text-slate-400">{new Date(session.createdAt).toLocaleDateString()}</span></div><p className="font-medium mt-2">{session.title || 'Untitled session'}</p><p className="text-xs font-semibold text-indigo-600 uppercase mt-1">{session.subject}</p><p className="text-sm text-slate-500 mt-2 line-clamp-2">{session.description || session.geminiAnalysis?.summary || session.transcript.slice(0, 110)}</p></Link>)}</div>}</aside></div></div>;
}
function Empty({ text }) { return <div className="empty-state">{text}</div>; }
