import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Edit3, Plus, Trash2 } from 'lucide-react';

const blankTask = { title: '', description: '', priority: 'MEDIUM', durationMinutes: 30 };
export default function SessionDetail() {
  const { id } = useParams(); const navigate = useNavigate(); const [session, setSession] = useState(null); const [editing, setEditing] = useState(false); const [form, setForm] = useState(null); const [taskForm, setTaskForm] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { try { const r = await fetch(`/api/learning-sessions/${id}`); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Failed to load session.'); setSession(data); setForm({ title: data.title || '', subject: data.subject, transcript: data.transcript }); } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, [id]);
  const change = e => setForm(c => ({ ...c, [e.target.name]: e.target.value }));
  async function saveSession(e) { e.preventDefault(); setSaving(true); setError(''); try { const r = await fetch(`/api/learning-sessions/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Failed to save session.'); setSession(data); setEditing(false); } catch (e) { setError(e.message); } finally { setSaving(false); } }
  async function deleteSession() { if (!window.confirm('Delete this learning session? This will also remove its associated learning tasks.')) return; setSaving(true); try { const r = await fetch(`/api/learning-sessions/${id}`, { method: 'DELETE' }); if (!r.ok) throw new Error('Failed to delete session.'); navigate('/'); } catch (e) { setError(e.message); setSaving(false); } }
  async function saveTask(e) { e.preventDefault(); setSaving(true); try { const isEdit = Boolean(taskForm.id); const url = isEdit ? `/api/tasks/${taskForm.id}` : '/api/tasks'; const body = isEdit ? taskForm : { ...taskForm, sessionId: id }; const r = await fetch(url, { method: isEdit ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Failed to save task.'); setTaskForm(null); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } }
  async function deleteTask(taskId) { if (!window.confirm('Delete this learning task?')) return; setSaving(true); try { const r = await fetch(`/api/tasks/${taskId}`, { method: 'DELETE' }); if (!r.ok) throw new Error('Failed to delete task.'); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } }
  if (error && !session) return <div className="alert-error">{error}</div>; if (!session) return <p className="text-slate-500">Loading session…</p>;
  const analysis = session.geminiAnalysis;
  return <div className="max-w-3xl mx-auto"><Link to="/" className="back-link"><ArrowLeft size={16} /> Back to Sessions</Link>{error && <div className="alert-error mt-4">{error}</div>}{editing ? <form className="card mt-5 space-y-4" onSubmit={saveSession}><h1 className="text-2xl font-bold">Edit Learning Session</h1><Field label="Title"><input name="title" value={form.title} onChange={change} /></Field><Field label="Subject"><input name="subject" value={form.subject} onChange={change} /></Field><Field label="Transcript"><textarea rows="10" name="transcript" value={form.transcript} onChange={change} /></Field><div className="flex gap-3 justify-end"><button type="button" className="button-secondary" onClick={() => setEditing(false)}>Cancel</button><button className="button-primary" disabled={saving}>{saving ? 'Saving…' : 'Save Changes'}</button></div></form> : <><section className="card mt-5"><div className="flex justify-between gap-4"><div><h1 className="text-3xl font-bold">{session.title || 'Untitled session'}</h1><p className="text-indigo-600 font-medium mt-1">{session.subject}</p><p className="text-sm text-slate-500 mt-2">Status: {session.status} · {new Date(session.createdAt).toLocaleDateString()}</p></div><div className="flex gap-2 h-fit"><button className="button-secondary" onClick={() => setEditing(true)}><Edit3 size={16} /> Edit</button><button className="button-secondary text-red-600" onClick={deleteSession} disabled={saving}><Trash2 size={16} /> Delete</button></div></div></section>{analysis && <section className="card mt-5 space-y-5"><div><h2 className="card-title">Summary</h2><p className="text-slate-600">{analysis.summary}</p></div><div><h2 className="card-title">Topics</h2>{analysis.topics.map((topic, i) => <div key={i} className="session mb-2"><p className="font-medium">{topic.name} <span className="badge">{topic.importance}</span></p><p className="text-sm text-slate-600 mt-1">{topic.description}</p></div>)}</div></section>}</>}
    <section className="card mt-5"><div className="flex justify-between items-center"><h2 className="card-title mb-0">Learning Tasks</h2><button className="button-primary" onClick={() => setTaskForm({ ...blankTask })}><Plus size={16} /> Add Learning Task</button></div>{taskForm && <TaskForm task={taskForm} setTask={setTaskForm} onSave={saveTask} saving={saving} onCancel={() => setTaskForm(null)} />}{session.tasks.length === 0 && !taskForm ? <div className="empty-state mt-4">No learning tasks yet.</div> : <div className="space-y-3 mt-4">{session.tasks.map(task => <article className="task" key={task.id}><div><p className="font-semibold">{task.title} <span className="badge">{task.priority}</span></p><p className="text-sm text-slate-600 mt-1">{task.description}</p><p className="text-xs text-slate-500 mt-2">{task.durationMinutes} min</p></div><div className="flex gap-2"><button className="button-secondary" onClick={() => setTaskForm({ ...task })}>Edit</button><button className="button-secondary text-red-600" onClick={() => deleteTask(task.id)} disabled={saving}>Delete</button></div></article>)}</div>}</section></div>;
}
function Field({ label, children }) { return <label className="block text-sm font-medium text-slate-700">{label}<div className="mt-1">{children}</div></label>; }
function TaskForm({ task, setTask, onSave, onCancel, saving }) { const change = e => setTask(t => ({ ...t, [e.target.name]: e.target.name === 'durationMinutes' ? Number(e.target.value) : e.target.value })); return <form className="session mt-4 space-y-3" onSubmit={onSave}><Field label="Title"><input name="title" value={task.title} onChange={change} /></Field><Field label="Description"><textarea name="description" rows="3" value={task.description || ''} onChange={change} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Priority"><select name="priority" value={task.priority} onChange={change}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></Field><Field label="Estimated minutes"><input type="number" min="5" name="durationMinutes" value={task.durationMinutes} onChange={change} /></Field></div><div className="flex justify-end gap-2"><button type="button" className="button-secondary" onClick={onCancel}>Cancel</button><button className="button-primary" disabled={saving}>{saving ? 'Saving…' : 'Save Task'}</button></div></form>; }
